# To run Terraform automatically with BitBucket Pipeline
# $SECRET_KEY -> secured JSON key (service account, configured in Repository Variables in BitBucket)
# $GOOGLE_CREDENTIALS -> /secret-key.json (configured in Repository Variables in BitBucket)
image: hashicorp/terraform:light
pipelines:
    branches:
        master:
            - step:
                name: Plan infrastructure changes
                script:
                    - echo $SECRET_KEY > $GOOGLE_CREDENTIALS
                    - terraform init
                    - terraform plan
            - step:
                name: Apply infrastructure changes
                trigger: manual
                script:
                    - echo $SECRET_KEY > $GOOGLE_CREDENTIALS
                    - terraform init
                    - terraform apply -auto-approve
